### ISSUE TITLE
Create application skeleton

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-network-operations#1]
- from hazdev-project-skeleton

**Comment by emartinez-usgs** [comment]
Some updates requested. See review on #10 for details.

**Comment by jmfee-usgs** [comment]
Related updates are in https://github.com/usgs/hazdev-project-skeleton/pull/2

**Comment by emartinez-usgs** [comment]
Merge usgs/hazdev-project-skeleton#2. These updates should be propagated to this project now as well.
