### ISSUE TITLE
Create index.php files for stations

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-network-operations#18]
Include static content:

- links
- station photos

**Comment by emartinez-usgs** [comment]
See: usgs/earthquake-website#427

**Comment by jmfee-usgs** [comment]
usgs/earthquake-website#427 was merged, but these pages do not yet include links or station photos.

**Comment by jmfee-usgs** [comment]
Station photos are handled separated, but links need to be added to station pages.

**Comment by jmfee-usgs** [comment]
Station photos are handled by a separate issue, links are still needed.

**Comment by emartinez-usgs** [comment]
See: https://github.com/usgs/earthquake-website/pull/450
