### ISSUE TITLE
Update pre-install to manage database

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-network-operations#2]
Three scripts:

- install.sql 
  create database schema
- uninstall.sql
  remove database schema
- update.sql
  modify existing database schema (not used yet)

During pre-install
- prompt whether to install/update schema 
- prompt whether to create read/write user
- (if installing or updating, prompt for admin user, make changes)

During uninstall
- prompt whether to remove schema
- prompt whether to remove read/write user
- (if removing, prompt for admin user, make changes)

**Comment by emartinez-usgs** [comment]
Schema/data install/uninstall seems okay, but still need to grant/revoke permissions for write-user. This write-user is what will be used to update the telemetry status in an automated fashion.
